{{- if .Values.include.kafka }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Release.Name }}-feedback-user
  labels:
    strimzi.io/cluster: {{ .Release.Name }}-feedback-app-messaging
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - resource:
          type: topic
          name: {{ .Release.Name }}-feedback-topic
          patternType: literal
        operation: Read
        host: '*'
      - resource:
          type: topic
          name: {{ .Release.Name }}-feedback-topic
          patternType: literal
        operation: Describe
        host: '*'
      - resource:
          type: topic
          name: {{ .Release.Name }}-feedback-topic
          patternType: literal
        operation: Write
        host: '*'
      - resource:
          type: topic
          name: {{ .Release.Name }}-feedback-topic
          patternType: literal
        operation: Create
        host: '*'
      - resource:
          type: group
          name: {{ .Release.Name }}-feedback-topic
          patternType: literal
        operation: Read
        host: '*'
      - resource:
          type: group
          name: {{ .Release.Name }}-feedback-topic
          patternType: literal
        operation: Write
        host: '*'
      - resource:
          type: group
          name: {{ .Release.Name }}-feedback-topic
          patternType: literal
        operation: Describe
        host: '*'
      - resource:
          type: group
          name: {{ .Release.Name }}-feedback-topic
          patternType: literal
        operation: Create
        host: '*'
      - resource:
          type: group
          name: {{ .Release.Name }}-feedback-persistence
          patternType: literal
        operation: Describe
        host: '*'
      - resource:
          type: group
          name: {{ .Release.Name }}-feedback-persistence
          patternType: literal
        operation: Create
        host: '*'
      - resource:
          type: group
          name: {{ .Release.Name }}-feedback-persistence
          patternType: literal
        operation: Read
        host: '*'
      - resource:
          type: group
          name: {{ .Release.Name }}-feedback-persistence
          patternType: literal
        operation: Write
        host: '*'
    type: simple
{{- end }}