apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Release.Name }}-feedback-app-messaging
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: '3.2'
    version: 3.2.3
    authorization:
      type: simple
    storage:
      type: ephemeral
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
  entityOperator:
    topicOperator:
      watchedNamespace: "{{ .Values.namespace }}"
    userOperator:
      watchedNamespace: "{{ .Values.namespace }}"
  zookeeper:
    storage:
      type: ephemeral
    replicas: 3
