{{- if .Values.include.kafkaConfigSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-kafka-config
stringData:
  kafka.bootstrap.servers: {{ .Release.Name }}-feedback-app-messaging-kafka-bootstrap-{{ .Values.namespace }}.apps.u3jjun8p.westeurope.aroapp.io
  kafka.user.name: {{ .Release.Name }}-feedback-user
  kafka.user.sasl.type: SCRAM-SHA-512
type: Opaque
{{- end }}