apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-mariadb
  labels:
    app: {{ .Release.Name }}-mariadb
spec:
  containers:
    - name: mariadb
      image: registry.redhat.io/rhel9/mariadb-105
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: {{ .Release.Name }}-mariadb-config
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: userPassword
              name: {{ .Release.Name }}-mariadb-config
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: {{ .Release.Name }}-mariadb-config
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rootPassword
              name: {{ .Release.Name }}-mariadb-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
spec:
  selector:
    app: {{ .Release.Name }}-mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
