{{- if .Values.include.database }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-mariadb-config
stringData:
  user: maria
  userPassword: password
  host: {{ .Release.Name }}-mariadb.{{ .Values.namespace }}.svc.cluster.local:3306
  database: feedback
  rootPassword: root
type: Opaque
{{- end }}