apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feedback-form-apps
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: argo-apps
    repoURL: https://github.com/marcoklaassen/feedback-form-config
    targetRevision: feature/hybrid-cloud
    directory:
      include: 'feedback-form-kafka.yaml'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
