resources:
  - ./../base
  - config-map.yaml
namePrefix: dev-

images:
  - name: feedback-persistence-image
    newName: image-registry.openshift-image-registry.svc:5000/feedback-app/feedback-persistence
    newTag: dev

replacements:
  - source:
      kind: ConfigMap
      name: dev-stage-config
      fieldPath: data.mariadbConfigSecretName
    targets:
      - select:
          kind: Service
          name: feedback-persistence
        fieldPaths:
          - spec.template.spec.containers.*.env.*.valueFrom.secretKeyRef.name

patchesJson6902:
- target:
    version: v1beta1
    group: sources.knative.dev
    kind: KafkaSource
    name: kafka-source-feedback
  patch: |-
    - op: replace
      path: /spec/net/sasl/user/secretKeyRef/name
      value: dev-kafka-config
    - op: replace
      path: /spec/net/sasl/type/secretKeyRef/name
      value: dev-kafka-config
    - op: replace
      path: /spec/net/sasl/password/secretKeyRef/name
      value: dev-feedback-user
    - op: replace
      path: /spec/net/tls/caCert/secretKeyRef/name
      value: dev-feedback-app-messaging-cluster-ca-cert
    - op: replace
      path: /spec/consumerGroup
      value: dev-feedback-persistence
    - op: replace
      path: /spec/bootstrapServers/0
      value: dev-feedback-app-messaging-kafka-bootstrap.feedback-app.svc.cluster.local:9092
    - op: replace
      path: /spec/topics/0
      value: dev-feedback-topic
    - op: replace
      path: /spec/sink/ref/name
      value: dev-feedback-persistence
