resources:
  - ./../base
namePrefix: dev-

images:
  - name: feedback-persistence-image
    newName: image-registry.openshift-image-registry.svc:5000/feedback-app/feedback-persistence-api
    newTag: cc01e9c975bc1592a19c40dcfa51a233fe514df0

patchesJson6902:
  - target:
      version: v1beta1
      group: sources.knative.dev
      kind: KafkaSource
      name: kafka-source-feedback
    patch: |-
      - op: replace
        path: /spec/net/sasl/user/secretKeyRef/name
        value: dev-kafka-config
      - op: replace
        path: /spec/net/sasl/type/secretKeyRef/name
        value: dev-kafka-config
      - op: replace
        path: /spec/net/sasl/password/secretKeyRef/name
        value: dev-feedback-user
      - op: replace
        path: /spec/net/tls/caCert/secretKeyRef/name
        value: dev-feedback-app-messaging-cluster-ca-cert
      - op: replace
        path: /spec/consumerGroup
        value: dev-feedback-persistence
      - op: replace
        path: /spec/bootstrapServers/0
        value: dev-feedback-app-messaging-kafka-tls-bootstrap-feedback-app.apps.u3jjun8p.westeurope.aroapp.io:443
      - op: replace
        path: /spec/topics/0
        value: dev-feedback-topic
      - op: replace
        path: /spec/sink/ref/name
        value: dev-feedback-persistence
  - target:
      version: v1
      group: serving.knative.dev
      kind: Service
      name: feedback-persistence
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
        value: dev-mariadb-config
      - op: replace
        path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/name
        value: dev-mariadb-config
      - op: replace
        path: /spec/template/spec/containers/0/env/2/valueFrom/secretKeyRef/name
        value: dev-mariadb-config
      - op: replace
        path: /spec/template/spec/containers/0/env/3/valueFrom/secretKeyRef/name
        value: dev-mariadb-config
