apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: feedback-persistence
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "5"
    spec:
      containers:
        - image: feedback-persistence-image
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: mariadb-config
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: userPassword
                  name: mariadb-config
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: mariadb-config
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: mariadb-config
