apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feedback-form-kafka
  namespace: feedback-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: feedback-app
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: dev
      valueFiles:
        - values.yaml
      values: |
        include:
          kafka: true
    path: feedback-form-apps/feedback-form-infrastructure
    repoURL: https://github.com/marcoklaassen/feedback-form-config
    targetRevision: feature/hybrid-cloud    
