apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feedback-form-infrastructure
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: feedback-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/marcoklaassen/feedback-form-config/tree/main/feedback-form-apps/feedback-form-infrastructure
    targetRevision: "1.16.0"
    chart: feedback-form-infrastructure
    helm:
      releaseName: dev
