apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feedback-persistence-api
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: feedback-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: feedback-form-apps/feedback-persistence-api/dev
    repoURL: https://github.com/marcoklaassen/feedback-form-config
    targetRevision: feature/hybrid-cloud
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    namespace: knative-serving-ingress
